name: Container entrypoint tests

on:
  pull_request:
    branches: [ main ]

jobs:
  entrypoint-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build test container
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8    # v6.19.2
        with:
          context: ./build
          file: ./build/ci/Dockerfile
          push: false
          tags: entrypoint-tests

      - name: Run Bats tests
        run: |
          docker run --rm entrypoint-tests
